### ISSUE TITLE
Enable TLS on webserver?

### ISSUE THREAD

**Issue by troy256** [DeployHubProject/DeployHub#1]
I'm trying out the Linux containerized version of DH Pro and couldn't find how to enable TLS in the online docs.  How do I set this up?

**Comment by sbtaylor15** [comment]
To enable TLS, a nginx frontend is used that has a proxy to DeployHub container.  nginx is where the SSL certs are placed.  Let me get you the setup instructions.

**Comment by sbtaylor15** [comment]
Are you running Kubernetes?  If so, we can put nginx and DeployHub in the same cluster to handle the TLS.   This is how our SaaS version is implemented.  Let me know if you want to go with a Kubernetes setup instead of a base docker setup.

**Comment by troy256** [comment]
Ultimately we might deploy DH on Kubernetes in which case I would probably use an Ingress to handle the SSL termination.  Right now I am deploying on base docker though, so any instructions related to that would be helpful.

**Comment by troy256** [comment]
I *think* I have it working using a nginx container with TLS enabled that reverse proxies to the DeployHub container.  Thanks for pointing me in the right direction.
